resources:
  App\Entity\Car:
    shortName: "cars"
    properties:
      id:
        identifier: true
    attributes:
      pagination_partial: false
      normalization_context:
        groups: [ "CARS::READ" ]
    itemOperations:
      get: ~
    collectionOperations:
      get: ~